// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/freshcart-features/OrderTracking.tsx": () => import("../components/mockups/freshcart-features/OrderTracking.tsx"),
  "./components/mockups/freshcart-features/ProductDetail.tsx": () => import("../components/mockups/freshcart-features/ProductDetail.tsx"),
  "./components/mockups/freshcart-features/ProfileDashboard.tsx": () => import("../components/mockups/freshcart-features/ProfileDashboard.tsx"),
  "./components/mockups/freshcart-features/ShopFilters.tsx": () => import("../components/mockups/freshcart-features/ShopFilters.tsx")
};
